- BookClub/BookList.Designer.cs
- BookClub/BookList.cs
- BookClub/BookList.resx
This commit introduces a new Windows Forms application with a `BookList` class that inherits from `Form`. The form includes controls for logging out, adding books, and displaying a book list title. The layout is defined in the designer file, and a resource file is added to manage application resources and metadata.
> Add BookList form for managing book lists

- BookClub/CreateAccount.Designer.cs
- BookClub/CreateAccount.cs
- BookClub/CreateAccount.resx
Introduces a new Windows Forms class `CreateAccount` in the `BookClub` namespace. The form includes controls for user input (first name, last name, username, password) and buttons for login and account creation.
Closes #3
> Issue#3 Add Create Account Form

- BookClub/Reviews.Designer.cs
- BookClub/Reviews.cs
- BookClub/Reviews.resx
This pull request introduces a new `Reviews` form to the `BookClub` application, which allows users to view and submit book reviews. The changes include the addition of the form's code-behind file, designer file, and associated resource file. Below is a summary of the most important changes:
* **`Reviews` Form Code-Behind (`BookClub/Reviews.cs`)**: Added a new `Reviews` class that inherits from `Form`, containing a constructor to initialize the form components.
* **`Reviews` Form Designer (`BookClub/Reviews.Designer.cs`)**: Added a detailed UI design for the `Reviews` form, including buttons (e.g., `btnLogout`, `btnBookList`, `btnSubmit`), labels (e.g., `lblBookTitle`, `lblReviews`), a text box for review input (`txtReview`), a panel for displaying reviews, and star rating picture boxes …
> Issue#4 Add Reviews Form

- BookClub/DiscussionBoard.Designer.cs
- BookClub/DiscussionBoard.cs
- BookClub/DiscussionBoard.resx
This pull request introduces a new `DiscussionBoard` feature to the BookClub application. The changes include the addition of a new form with its layout, logic, and associated resources to support discussion functionality.
* **Form Layout and UI Components**:
- Added a new `DiscussionBoard` form with various UI components, including buttons (`btnLogout`, `btnReviews`, `btnBookList`, `btnSubmit`), labels (`lblBookTitle`, `lblDiscussionBoard`, `lblISBN`, `lblAuthor`, `lblDescription`), a `PictureBox` for book thumbnails, a `TextBox` for discussion posts, and a `Panel` for displaying discussion content. (`BookClub/DiscussionBoard.Designer.cs`, [BookClub/DiscussionBoard.Designer.csR1-R195](diffhunk://#diff-3de1543ff34751ff9584cde6a46210efc0bd746859c9c038d85a73a8cc8c9d2fR1-R195))
* **Form …
> Issue#5 Add Discussion Board Form

- BookClub/AddBook.Designer.cs
- BookClub/AddBook.cs
- BookClub/BookList.Designer.cs
- BookClub/BookList.cs
- BookClub/CreateAccount.Designer.cs
- BookClub/CreateAccount.cs
- BookClub/DiscussionBoard.Designer.cs
- BookClub/DiscussionBoard.cs
- BookClub/Login.Designer.cs
- BookClub/Login.cs
- BookClub/Reviews.Designer.cs
- BookClub/Reviews.cs
This pull request introduces event handlers to all major navigation buttons across the application's forms, enabling users to navigate between forms such as Login, BookList, AddBook, CreateAccount, Reviews, and DiscussionBoard. It also ensures that closing any form will exit the application, providing a consistent user experience.
The most important changes are:
**Navigation and Event Handling:**
* Added `Click` event handlers for navigation buttons (`Login`, `Logout`, `Book List`, `Add Book`, `Create Account`, `Submit`, `Open Discussion Board`, and `Back to Reviews`) in all relevant `.Designer.cs` files, enabling navigation between forms. [[1]](diffhunk://#diff-27106321d5bff4cbb008fe1cee79cc913ea3e2773a346be449163bc5d1c39e39R49) …
> Issue#38 Add Navigation Between Forms

- BookClub/BookClub.csproj
- BookClub/BookList.Designer.cs
- BookClub/BookList.cs
This pull request enhances the `BookList` form by connecting it to a SQL Server database and dynamically displaying the list of books. The changes include adding the necessary SQL client dependency, refactoring UI components for clarity, and implementing a method to fetch and display books from the database.
**Database integration and dynamic book list:**
* Added a reference to the `Microsoft.Data.SqlClient` package in `BookClub.csproj` to enable SQL Server connectivity.
* In `BookList.cs`, imported `Microsoft.Data.SqlClient` and implemented the `PopulateBookList` method to query the `Books` table and dynamically generate book buttons in the panel. This method is called on form initialization. [[1]](diffhunk://#diff-e7d9479458c64506d1d3dbcd383c273e033ebe38d6f6e4b66c402d1a84dd3b2fR10) …
> Issue#13 Add Books to Book List

- BookClub/AddBook.cs
- BookClub/BookClub.csproj
- BookClub/BookList.cs
- BookClub/CreateAccount.cs
- BookClub/Data/AppDbContext.cs
- BookClub/Data/AppDbContextFactory.cs
- BookClub/DiscussionBoard.cs
- BookClub/Login.cs
- BookClub/Models/Account.cs
- BookClub/Models/Book.cs
- BookClub/Program.cs
- BookClub/Reviews.cs
- BookClub/appsettings.json
- README.md
This pull request introduces Entity Framework Core to the Book Club application, refactors the codebase to use dependency injection for form navigation and data access, and adds models and configuration for persistent storage. The main changes improve maintainability, enable database-backed data management, and set up the project for future scalability.
* Added Entity Framework Core to the project, including configuration for SQL Server and required NuGet packages in `BookClub.csproj` and a new `appsettings.json` for connection strings. [[1]](diffhunk://#diff-d589568f1b3474806646af72fa83d4af60d0b51de323a3d8dfe8d3ecac967e38R13-R20) [[2]](diffhunk://#diff-d589568f1b3474806646af72fa83d4af60d0b51de323a3d8dfe8d3ecac967e38R38-R43) [[3]](diffhunk://#diff-00fc7ef144c0b552168d245f66485301fe18a14ca1 …
> Add entity framework core and configure database

- BookClub.sln
- BookClub/Login.cs
- BookClub/Program.cs
- BookClub/Repositories/AccountsRepository.cs
- BookClubTests/BookClubTests.csproj
- BookClubTests/Repositories/AccountsRepositoryTests.cs
This pull request introduces a new repository pattern for managing accounts and adds a comprehensive test project for the `AccountsRepository`. The changes improve separation of concerns, enable easier unit testing, and enhance maintainability by moving data access logic out of the UI layer.
* Added new `AccountsRepository` class in `BookClub/Repositories/AccountsRepository.cs` to encapsulate CRUD operations for `Account` entities. This replaces direct usage of `AppDbContext` in the login form and other areas.
* Updated dependency injection setup in `BookClub/Program.cs` to register `AccountsRepository` as a scoped service.
* Modified the `Login` form (`BookClub/Login.cs`) to use `AccountsRepository` instead of directly accessing the database context, improving code modularity and …
> Implement Account CRUD Functions

- BookClub/Forms/BookList.Designer.cs
- BookClub/Forms/BookList.cs
- BookClub/Forms/EditAccount.Designer.cs
- BookClub/Forms/EditAccount.cs
- BookClub/Forms/EditAccount.resx
- BookClub/Program.cs
This pull request introduces an "Edit Account" feature to the application, allowing users to access and modify their account information from the book list screen. The main changes include adding a new `EditAccount` form, updating navigation to support it, and registering the form for dependency injection.
**New Feature: Edit Account**
* Added a new form `EditAccount` with fields for first name, last name, username, email, and buttons for saving changes, resetting password, logging out, and returning to the book list. (`BookClub/Forms/EditAccount.Designer.cs`, `BookClub/Forms/EditAccount.cs`, `BookClub/Forms/EditAccount.resx`) [[1]](diffhunk://#diff-8ec912be5ec97b1734f11a56287726e61f21149e1b8a59e94911082aa1186633R1-R199) [[2]](diffhunk://#diff-9c119873b7abc17727115183d2d8feaca4e8d339680380 …
> Issue#63 Add New Forms - Edit Account

- BookClub/Forms/Login.cs
Closes #69
Refactor the login process by adding a new `TryLogin` method that checks for empty fields, verifies account existence, and validates the password. This change replaces the previous inline login check, enhancing code readability and maintainability.
Add login error handling to btnLogin_Click method
Enhance the `btnLogin_Click` method in the `Login` class by adding a comment for clarity and implementing a conditional check for login failures. If the login attempt fails, an error message is displayed to the user, and the method exits early to prevent further processing.
> Improve login functionality in Login.cs

- BookClub/Forms/AddBook.cs
- BookClub/Models/Book.cs
- BookClub/Program.cs
Closes #73 
This pull request refactors the book addition workflow to use a repository pattern and improves validation and documentation. The main changes include switching from direct `AppDbContext` usage to a new `BookRepository`, adding input validation for book details, and enhancing the documentation for the `Book` model.
**Refactor to repository pattern:**
* The `AddBook` form now uses a `BookRepository` instead of directly accessing `AppDbContext`, promoting better separation of concerns and testability. (`BookClub/Forms/AddBook.cs`, [BookClub/Forms/AddBook.csR2-R13](diffhunk://#diff-979bafbe1969742938995f61ed590f661986cea7007cd6604d52c77e6ce029ccR2-R13))
* `BookRepository` is registered as a scoped service in dependency injection, enabling its use throughout the application. …
> #73 add book logic

- BookClub/Forms/BookList.cs
- BookClub/Forms/EditAccount.Designer.cs
- BookClub/Forms/EditAccount.cs
- BookClub/Forms/Login.cs
- BookClub/Program.cs
- BookClub/Resources/UserContext.cs
This pull request introduces user session management and implements account deletion functionality in the BookClub application. The main changes include adding a `UserContext` class for tracking the logged-in user, refactoring form constructors to use this context, and enabling users to delete their accounts through the UI.
**User session management:**
* Introduced a new `UserContext` class to store the currently logged-in user's account, registered as a singleton service for application-wide access (`BookClub/Resources/UserContext.cs`, `BookClub/Program.cs`). [[1]](diffhunk://#diff-75d9638c62f757539588a392a9052ebfe3b35f6572815ba6c41f32f975ed24eaR1-R7) [[2]](diffhunk://#diff-c0178c2f07e53338beaa27c3179383e2b69cc5be55e3ee3183e3317f060b3d79R49-R51)
* Refactored constructors for `BookList` …
> Issue#85 Add Delete Account Button

- BookClub/Forms/CreateAccount.Designer.cs
- BookClub/Forms/CreateAccount.cs
This pull request updates the `CreateAccount` form to support email input and integrates it with the application's account management logic. The most important changes include adding an email field to the UI, updating the form layout, and implementing logic to create a new account using the `AccountsRepository` and `UserContext`.
**UI Enhancements:**
* Added a new `TextBox` control `txtEmail` to the form for email input, including its placement, properties, and initialization. [[1]](diffhunk://#diff-175e149cdb3eabc8c200d0aa812dffe03da2798b0acbf78e205f2594342e815fR39) [[2]](diffhunk://#diff-175e149cdb3eabc8c200d0aa812dffe03da2798b0acbf78e205f2594342e815fL97-R117) [[3]](diffhunk://#diff-175e149cdb3eabc8c200d0aa812dffe03da2798b0acbf78e205f2594342e815fR140)
* Updated the positions of existing …
> Issue#102 Implement Create Account Functionality

- BookClub/Data/AppDbContext.cs
- BookClub/Data/Configurations/AccountsConfiguration.cs
- BookClub/Data/Configurations/BooksConfiguration.cs
- BookClub/Data/Configurations/ReviewsConfiguration.cs
- BookClub/Migrations/20250829001230_AddedReviews.Designer.cs
- BookClub/Migrations/20250829001230_AddedReviews.cs
- BookClub/Models/Review.cs
- BookClub/Repositories/AccountsRepository.cs
- BookClub/Repositories/BookRepository.cs
- BookClubTests/Repositories/AccountsRepositoryTests.cs
- BookClubTests/Repositories/BookRepositoryTests.cs
Closes #105
This pull request refactors how entity configurations and seed data are managed in the database layer, introduces a new `Review` entity, and updates migrations to reflect these changes. The most important changes are grouped below.
**Entity Configuration and Seed Data Refactoring:**
* Moved the configuration and seed data for `Account`, `Book`, and `Review` entities from `AppDbContext` into dedicated configuration classes: `AccountsConfiguration`, `BooksConfiguration`, and `ReviewsConfiguration`. These are now applied using `modelBuilder.ApplyConfigurationsFromAssembly` in `AppDbContext`. This makes the codebase more modular and maintainable. [[1]](diffhunk://#diff-79db0fd53f89fb3870382e559cc92f33d312265200ae81a9fd242501c93b6b0cR3-R16) …
> #105 add migrations added reviews

- BookClub/Forms/BookList.cs
- BookClub/Program.cs
- BookClub/Resources/BookContext.cs
This pull request refactors how the currently selected book is managed and displayed in the `BookList` form. It introduces a new `BookContext` class to store the selected book, updates dependency injection to include this context, and simplifies book retrieval by using the `BookRepository`. The changes improve code maintainability and make it easier to access the selected book throughout the application.
Dependency injection and context management:
* Added a new `BookContext` class to store the currently selected book and registered it as a singleton in the dependency injection container (`BookClub/Resources/BookContext.cs`, `BookClub/Program.cs`). [[1]](diffhunk://#diff-f53dfc576b29932ad22b6b06e5178093791c6b8d1aee6ed6a4751c4e9a4af781R1-R10) …
> Issue#109 Add Book Context Class

- BookClub/Models/Review.cs
- BookClub/Repositories/AccountsRepository.cs
- BookClub/Repositories/BookRepository.cs
- BookClub/Repositories/ReviewsRepository.cs
- BookClubTests/Repositories/ReviewsRepositoryTests.cs
Closes #54
This pull request introduces a new repository for managing book reviews, including full CRUD operations, a corresponding data transfer object for updates, and comprehensive unit tests to ensure repository correctness. It also includes a small fix in the book repository and a minor cleanup in the accounts repository.
**Review Management Functionality**
* Added a new `ReviewsRepository` class to handle create, read, update, and delete operations for reviews, including validation for updates using the new `ReviewUpdateDTO` type.
* Introduced the `ReviewUpdateDTO` class to encapsulate and validate review update data, enforcing rating and comment constraints.
**Testing**
* Added a new test class `ReviewsRepositoryTests` with unit tests for all repository methods, ensuring correct …
> #54 implement crud functionalities reviews

- BookClub/Forms/Reviews.cs
- BookClub/Resources/BookContext.cs
This pull request refactors the `Reviews` form to use repository and context classes for dependency injection and data access, instead of direct database queries. It also makes `BookContext` publicly accessible, enabling better sharing of the current book state across the application.
Dependency injection and data access improvements:
* Refactored the `Reviews` constructor to accept `UserContext`, `AccountsRepository`, `BookRepository`, and `BookContext` as dependencies, replacing the previous direct use of `AppDbContext` and book ID. The form now retrieves the current book from `BookContext` rather than querying the database directly.
* Updated the `LoadBookInfo` method to use the `Book` object from `BookContext` instead of executing a raw SQL query, simplifying and decoupling data …
> Issue#116 Refactor Reviews Form

- BookClub/Forms/EditBook.Designer.cs
- BookClub/Forms/EditBook.cs
- BookClub/Forms/EditBook.resx
Updated `EditBook.cs` to implement a form for editing book details, including logout and navigation event handlers. Modified `EditBook.Designer.cs` to define the layout and components of the form, such as text boxes and buttons. Added `EditBook.resx` for resource management metadata.
Closes #122
> Issue#122 Create EditBook Form

- BookClub/Forms/BookList.Designer.cs
- BookClub/Forms/BookList.cs
- Introduced buttons for deleting, editing, and adding reviews in the `BookList` form with their event handlers.
- Adjusted layout and sizes of existing UI elements for improved alignment.
- Updated form properties to fit the new layout.
- Added a `_selectedBook` field to track the currently selected book.
- Enhanced button click logic to enable new actions based on book selection.
> Add book management buttons and update layout

- BookClub/Forms/EditBook.Designer.cs
- BookClub/Forms/EditBook.cs
This pull request updates the `EditBook` form to improve the user experience when editing book details. The main changes include renaming and updating the submit button, refactoring the form to use dependency injection for repositories and context, and implementing logic to update only changed fields. It also adds a helper to populate textboxes with placeholder values based on the current book.
**UI/UX Improvements:**
* Renamed the submit button to `btnSaveChanges`, updated its label to "Save Changes", and connected it to a new click handler for saving changes. (`BookClub/Forms/EditBook.Designer.cs`) [[1]](diffhunk://#diff-8b9c84b3de7ae5606db5540adf476e3b95e6566f33dd15a4f6a7039871dc86d1L32-R32) [[2]](diffhunk://#diff-8b9c84b3de7ae5606db5540adf476e3b95e6566f33dd15a4f6a7039871dc86d1L54-R62) …
> Issue#24 Implement Edit Book Functionality

- BookClub/Repositories/AccountsRepository.cs
Closes #96
Added detailed XML documentation comments to the
AccountsRepository class and its methods. This
improves code readability and provides clear
descriptions of the functionality for managing
accounts, including CRUD operations and
parameter details.
> Enhance XML documentation in AccountsRepository

- BookClub/Forms/BookList.cs
Closes #138 and #87
Updated the `BookList` class in `BookList.cs` to improve documentation with added summaries and remarks. Removed the dependency on `AccountsRepository` in the constructor for simplification. Enhanced the `PopulateBookList` method to dynamically create buttons for each book and added event handling for selecting books and enabling action buttons. Introduced `EnableBookActionButtons` and `DisableBookActionButtons` methods for better management of action button states. Refined delete functionality to refresh the book list and disable action buttons post-deletion for improved user experience.
> Enhance BookList class documentation and functionality

- BookClub/Forms/CreateAccount.cs
Closes #88
Updated the CreateAccount class with XML documentation for better readability. Removed the UserContext parameter from the constructor and initialized the user context within the method. Added a new ValidateInputs method to validate user inputs for account creation. Updated logic to set the current user context after successful account creation and transition to the BookList form.
> Refactor CreateAccount class and enhance validation

- BookClub/Forms/EditAccount.cs
Closes #90 
Enhanced XML documentation, improved method readability, and streamlined validation logic. Updated the PopulateTextboxes method to clear textboxes before setting placeholders. Consistent formatting applied to event handlers for better code organization.
> Refactor EditAccount.cs for clarity and organization

- BookClub/Forms/Reviews.cs
- BookClub/Program.cs
This pull request enhances the `Reviews` form to display all reviews for a book dynamically and ensures the `ReviewsRepository` is properly registered for dependency injection. The main focus is on improving the user interface by showing existing reviews with user names, comments, star ratings, and timestamps.
**User interface improvements:**
* Added the `PopulateReviewsPanel` method to `Reviews.cs`, which dynamically creates and displays a list of reviews for the current book, including reviewer username, comment, date, and a visual star rating for each review.
* Called `PopulateReviewsPanel()` in the `Reviews` form constructor to ensure reviews are loaded and displayed when the form opens.
**Dependency injection updates:**
* Registered `ReviewsRepository` as a scoped service in the …
> Issue#140 Make Reviews Panel Functional

- BookClub/Forms/EditReview.Designer.cs
- BookClub/Forms/EditReview.cs
- BookClub/Forms/EditReview.resx
Introduces a new Windows Forms class `EditReview` in the `BookClub.Forms` namespace. The form includes buttons for "Reviews," "Logout," "Save Changes," and "Delete Review," along with picture boxes for star ratings and a text box for review input. A resource file (`EditReview.resx`) is also added to manage metadata and schema for the form's resources.
Closes #147
> Issue#147 Create Edit Review Form

- BookClub/Data/AppDbContext.cs
- BookClub/Data/Configurations/DiscussionsConfiguration.cs
- BookClub/Forms/BookList.Designer.cs
- BookClub/Forms/BookList.cs
- BookClub/Forms/DiscussionBoard.Designer.cs
- BookClub/Forms/DiscussionBoard.cs
- BookClub/Migrations/20250829082115_SeedDiscussions.Designer.cs
- BookClub/Migrations/20250829082115_SeedDiscussions.cs
- BookClub/Models/Discussion.cs
- BookClub/Program.cs
- BookClub/Repositories/DiscussionsRepository.cs
Closes #76
This pull request introduces a new "Discussion" feature to the Book Club app, allowing users to view and post discussions related to each book. The changes span database schema updates, UI modifications, and backend logic to support displaying and adding discussions. Additionally, there are some UI refinements to existing forms.
**Discussion Feature Implementation**
* Added a new `Discussions` table to the database, including a migration to seed initial discussion data for five books. (`BookClub/Migrations/20250829082115_SeedDiscussions.cs`)
* Registered a new `DbSet<Discussion>` in the `AppDbContext` and provided configuration and seed data through `DiscussionsConfiguration`. (`BookClub/Data/AppDbContext.cs`, `BookClub/Data/Configurations/DiscussionsConfiguration.cs`) …
> #76 implement business logic discussion board

- BookClub/Forms/DiscussionBoard.Designer.cs
- BookClub/Forms/DiscussionBoard.cs
Closes #154
Updated the DiscussionBoard class to replace the btnSubmit with btnSubmitPost and added btnEditPost and btnDeletePost. Adjusted tab indices for controls and defined properties for new buttons.
Initialized _selectedBook to null and called LoadBookInfo and PopulateDiscussionsPanel after form initialization. Added methods to enable/disable post action buttons and updated btnSubmit_Click for validation.
Introduced SelectDiscussionGroupBox for visual feedback on selected discussions, and implemented event handlers for editing and deleting posts.
> Refactor DiscussionBoard with new post management features

- BookClub/Forms/EditReview.Designer.cs
- BookClub/Forms/EditReview.cs
- BookClub/Forms/Reviews.cs
- BookClub/Handlers/StarSystemController.cs
This pull request introduces a reusable star rating controller to centralize and simplify the star rating logic across the application. The main changes include refactoring both the `EditReview` and `Reviews` forms to use the new `StarSystemController`, improving code maintainability and consistency. Additionally, it enhances the review editing workflow and input validation.
**Star rating system refactor:**
* Introduced a new `StarSystemController` class in `BookClub/Handlers/StarSystemController.cs` to encapsulate all star rating logic, including UI updates and event handling. This controller is now used in both the `EditReview` and `Reviews` forms.
* Refactored `BookClub/Forms/Reviews.cs` to replace the previous star rating logic with the new `StarSystemController`, removing custom …
> Issue#149 Implement Edit Review Functionality
